# Generated by Django 4.2 on 2025-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authentications",
            fields=[
                (
                    "authentication_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_credential_id", models.IntegerField()),
                ("access_token", models.CharField(max_length=50)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "authentications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("provider_id", models.AutoField(primary_key=True, serialize=False)),
                ("provider_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "provider",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "number_2fa_id",
                    models.AutoField(
                        db_column="2fa_id", primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("method", models.CharField(max_length=50)),
                ("secret_key", models.CharField(max_length=50)),
                ("is_active", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "two_factor_auth",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type_id", models.IntegerField(blank=True, null=True)),
                ("user_status_id", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAgreement",
            fields=[
                ("agreement_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("terms_version", models.CharField(max_length=50)),
                ("agreed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_agreement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserCredentials",
            fields=[
                (
                    "user_credential_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField()),
                ("provider_id", models.IntegerField()),
                ("username", models.CharField(max_length=50)),
                ("password_hash", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=11)),
                ("email_address", models.CharField(max_length=50)),
                ("verified", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("password_expires_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.IntegerField()),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("is_locked", models.IntegerField(blank=True, null=True)),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_credentials",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField()),
                ("firstname", models.CharField(max_length=50)),
                ("middlename", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSessions",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("device_id", models.IntegerField()),
                ("token", models.CharField(max_length=50)),
                ("is_persistent", models.IntegerField()),
                ("ip_address", models.CharField(max_length=50)),
                ("ip_location", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                ("user_status_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_status_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "user_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("user_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.CharField(max_length=50)),
                ("session_policy_id", models.IntegerField()),
            ],
            options={
                "db_table": "user_type",
                "managed": False,
            },
        ),
    ]
