# Generated by Django 4.2 on 2025-11-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": True},
        ),
    ]
