# Generated by Django 4.2 on 2025-11-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authentications",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="twofactorauth",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="useragreement",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="usercredentials",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="usersessions",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="userstatus",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="usertype",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.usercredentials",
            ),
        ),
    ]
