# Generated by Django 4.2 on 2025-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_alter_authentications_options_alter_provider_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_status_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercredentials",
            name="failed_attempts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercredentials",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="usercredentials",
            name="provider_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercredentials",
            name="verified",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
