# Generated by Django 4.2 on 2025-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_user_status_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredentials",
            name="password_hash",
            field=models.CharField(max_length=255),
        ),
    ]
